---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    version: 9-jdk

inputs:
- name: beak-source

run:
  dir: beak-source
  path: sh
  args:
  - -exc
  - |
    ./gradlew beak:testH2
