---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/cosee-concourse/dind
    tag: latest

inputs:
- name: beak-source

params:
  MYSQL_VERSION:

run:
  path: sh
  args:
  - -exc
  - |
    source /docker-lib.sh
    start_docker

    docker network create beak

    docker run -d --name mysql -e MYSQL_ALLOW_EMPTY_PASSWORD=yes --network beak mysql:$MYSQL_VERSION

    docker run -v $(pwd)/beak-source:/source -i --network beak openjdk:9-jdk-slim bash -ex <<CMD
      cd /source
      ./gradlew beak:testMySQL -Ptest.db.mysql="mysql://root:@mysql.beak:3306/?serverTimezone=UTC&useSSL=false"
    CMD
