---
jobs:
- name: H2 tests
  plan:
  - get: beak-source
    trigger: true
  - task: Test H2
    file: beak-source/pipeline/tasks/test-h2.yml
- name: MySQL 5.7 tests
  plan:
  - get: beak-source
    trigger: true
  - aggregate:
    - task: Test MySQL 5.7.21
      privileged: true
      file: beak-source/pipeline/tasks/test-mysql.yml
      params: {MYSQL_VERSION: 5.7.21}
    - task: Test MySQL 5.7.20
      privileged: true
      file: beak-source/pipeline/tasks/test-mysql.yml
      params: {MYSQL_VERSION: 5.7.20}
    - task: Test MySQL 5.7.19
      privileged: true
      file: beak-source/pipeline/tasks/test-mysql.yml
      params: {MYSQL_VERSION: 5.7.19}
    - task: Test MySQL 5.7.18
      privileged: true
      file: beak-source/pipeline/tasks/test-mysql.yml
      params: {MYSQL_VERSION: 5.7.18}
    - task: Test MySQL 5.7.17
      privileged: true
      file: beak-source/pipeline/tasks/test-mysql.yml
      params: {MYSQL_VERSION: 5.7.17}
    - task: Test MySQL 5.7.16
      privileged: true
      file: beak-source/pipeline/tasks/test-mysql.yml
      params: {MYSQL_VERSION: 5.7.16}
    - task: Test MySQL 5.7.15
      privileged: true
      file: beak-source/pipeline/tasks/test-mysql.yml
      params: {MYSQL_VERSION: 5.7.15}
    - task: Test MySQL 5.7.14
      privileged: true
      file: beak-source/pipeline/tasks/test-mysql.yml
      params: {MYSQL_VERSION: 5.7.14}
    - task: Test MySQL 5.7.13
      privileged: true
      file: beak-source/pipeline/tasks/test-mysql.yml
      params: {MYSQL_VERSION: 5.7.13}
    - task: Test MySQL 5.7.12
      privileged: true
      file: beak-source/pipeline/tasks/test-mysql.yml
      params: {MYSQL_VERSION: 5.7.12}
    - task: Test MySQL 5.7.11
      privileged: true
      file: beak-source/pipeline/tasks/test-mysql.yml
      params: {MYSQL_VERSION: 5.7.11}
    - task: Test MySQL 5.7.10
      privileged: true
      file: beak-source/pipeline/tasks/test-mysql.yml
      params: {MYSQL_VERSION: 5.7.10}
    - task: Test MySQL 5.7.9
      privileged: true
      file: beak-source/pipeline/tasks/test-mysql.yml
      params: {MYSQL_VERSION: 5.7.9}

- name: PostgreSQL 10 tests
  plan:
  - get: beak-source
    trigger: true
  - aggregate:
    - task: Test PostgreSQL 10.3
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 10.3-alpine}
    - task: Test PostgreSQL 10.2
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 10.2-alpine}
    - task: Test PostgreSQL 10.1
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 10.1-alpine}
    - task: Test PostgreSQL 10.0
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 10.0-alpine}

- name: PostgreSQL 9.6 tests
  plan:
  - get: beak-source
    trigger: true
  - aggregate:
    - task: Test PostgreSQL 9.6.8
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 9.6.8-alpine}
    - task: Test PostgreSQL 9.6.7
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 9.6.7-alpine}
    - task: Test PostgreSQL 9.6.6
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 9.6.6-alpine}
    - task: Test PostgreSQL 9.6.5
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 9.6.5-alpine}
    - task: Test PostgreSQL 9.6.4
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 9.6.4-alpine}
    - task: Test PostgreSQL 9.6.3
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 9.6.3-alpine}
    - task: Test PostgreSQL 9.6.2
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 9.6.2-alpine}

- name: PostgreSQL 9.5 tests
  plan:
  - get: beak-source
    trigger: true
  - aggregate:
    - task: Test PostgreSQL 9.5.12
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 9.5.12-alpine}
    - task: Test PostgreSQL 9.5.11
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 9.5.11-alpine}
    - task: Test PostgreSQL 9.5.10
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 9.5.10-alpine}
    - task: Test PostgreSQL 9.5.9
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 9.5.9-alpine}
    - task: Test PostgreSQL 9.5.8
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 9.5.8-alpine}
    - task: Test PostgreSQL 9.5.7
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 9.5.7-alpine}
    - task: Test PostgreSQL 9.5.6
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 9.5.6-alpine}
    - task: Test PostgreSQL 9.5.5
      privileged: true
      file: beak-source/pipeline/tasks/test-postgresql.yml
      params: {POSTGRESQL_VERSION: 9.5.5-alpine}

- name: publish
  serial: true
  plan:
  - get: beak-source
    passed:
    - H2 tests
    - MySQL 5.7 tests
    - PostgreSQL 10 tests
    - PostgreSQL 9.6 tests
    - PostgreSQL 9.5 tests
    trigger: true
  - task: get version numbers
    file: beak-source/pipeline/tasks/get-version-numbers.yml
  - task: build and publish
    file: beak-source/pipeline/tasks/build-publish.yml
    params:
      BINTRAY_USER: ((bintray-user))
      BINTRAY_API_KEY: ((bintray-api-key))

resources:
- name: beak-source
  type: git
  source:
    uri: https://github.com/codebandits/beak.git
    branch: master
